[package]
name = "redefmt-logger"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
alloc = []

[lints]
workspace = true

[dependencies]
redefmt-common.workspace = true

critical-section = "1.2"

[dev-dependencies]
redefmt-common = { workspace = true, features = ["testing"] }
redefmt-logger = { path = ".", features = ["alloc"] }

bytes = { version = "1.10", default-features = false }
num-traits = "0.2"
