[package]
name = "redefmt-logger"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
redefmt-common.workspace = true

critical-section = "1.2"

[dev-dependencies]
bytes = { version = "1.10", default-features = false }
critical-section = { version = "1.2", features = ["std"] }
