[package]
name = "redefmt-args"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
builder = ["dep:bon"]
serde = ["dep:serde"]
syn = ["dep:proc-macro2", "dep:syn"]

[lints]
workspace = true

[dependencies]
bit-set = { version = "0.8", default-features = false }
derive-getters = "0.5"
hashbrown = { version = "0.15", default-features = false, features = ["default-hasher"] }
thiserror = { version = "2.0", default-features = false }
unicode-xid = "0.2"

# feature: builder
bon = { version = "3.6", default-features = false, optional = true }

# feature: serde
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"], optional = true }

# feature: syn
proc-macro2 = { version = "1.0", optional = true }
syn = { version = "2.0", default-features = false, features = ["extra-traits", "parsing", "printing"], optional = true }

[dev-dependencies]
redefmt-args = { path = ".", features = ["builder", "serde", "syn"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
