[package]
name = "redefmt-common"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
# Internal
redefmt-args.workspace = true

# External
hashbrown = { version = "0.15", default-features = false, features = ["default-hasher"] }
uuid = { version = "1.16", default-features = false }
